import Head from "next/head";
import { blogPosts } from "../../lib/data";

export default function BlogPage({ title, date, content }) {
   return (
      <div>
         <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <main>
            <h1>{title}</h1>
            <div>{content}</div>
            <div>{date}</div>
         </main>
      </div>
   );
}

export async function getStaticProps(context) {
   const { params } = context;
   return {
      props: blogPosts.find((blog) => blog.slug === params.slug),
   };
}

export async function getStaticPaths() {
   const res = {
      paths: blogPosts.map((blog) => ({
         params: { slug: blog.slug },
      })),
      fallback: false,
   };

   return res;
}
