import Head from "next/head";
import Link from "next/link";
import { format, parseISO } from "date-fns";
import { getAllPosts } from "../lib/data";

export default function Home({ posts }) {
  return (
    <div>
      <Head>
        <title> Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="space-y-4">
        {posts.map((blog) => (
          <BlogListItem key={blog.slug} {...blog} />
        ))}
      </div>
    </div>
  );
}

function BlogListItem({ title, slug, date, content }) {
  return (
    <div className="border border-black-800 shadow rounded-md p-5 hover:shadow-lg hover:border-indigo-800 transition-colors">
      <div>
        <Link href={`/blog/${slug}`}>
          <a className="text-lg font-bold">{title}</a>
        </Link>
      </div>
      <div className="text-gray-400 text-sm">
        {format(parseISO(date), "MMMM do, uuu")}
      </div>
      <div>{content}</div>
    </div>
  );
}

export async function getStaticProps() {
  const allPosts = getAllPosts();

  return {
    props: {
      posts: allPosts.map(({ data, content, slug }) => ({
        title: data.title,
        date: data.date.toISOString(),
        content: content,
        slug: slug,
      })),
    },
  };
}
