import Head from "next/head";
import Link from "next/link";
import { format, parseISO, add } from "date-fns";
import { blogPosts } from "../lib/data";

export default function Home() {
   return (
      <div>
         <Head>
            <title> Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <div className="space-y-4">
            {blogPosts.map((blog) => (
               <BlogListItem key={blog.slug} {...blog} />
            ))}
         </div>
      </div>
   );
}

function BlogListItem({ title, slug, date, content }) {
   return (
      <div className="border border-black-800 shadow rounded-md p-5 hover:shadow-lg hover:border-indigo-800 transition-colors">
         <div>
            <Link href={`/blog/${slug}`}>
               <a className="text-lg font-bold">{title}</a>
            </Link>
         </div>
         <div className="text-gray-400 text-sm">
            {format(parseISO(date), "MMMM do, uuu")}
         </div>
         <div>{content}</div>
      </div>
   );
}
